// <auto-generated />
using System;
using MVCP_BookStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCP_BookStore.Migrations
{
    [DbContext(typeof(BookStoreDBContext))]
    [Migration("20250222003556_CartAdded")]
    partial class CartAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVCP_BookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Astrid Lindgren",
                            DatePublished = new DateTime(2013, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9789129688313",
                            ImageUrl = "/images/lejonhjärta.jpg",
                            Language = "Swedish",
                            Price = 139,
                            Title = "Bröderna Lejonhjärta"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J. R. R. Tolkien",
                            DatePublished = new DateTime(1991, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9780261102354",
                            ImageUrl = "/images/lotr.jpg",
                            Language = "English",
                            Price = 100,
                            Title = "The Fellowship of the Ring"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dennis Lehane",
                            DatePublished = new DateTime(2011, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9780062068408",
                            ImageUrl = "/images/mystic-river.jpg",
                            Language = "English",
                            Price = 91,
                            Title = "Mystic River"
                        },
                        new
                        {
                            Id = 4,
                            Author = "John Steinbeck",
                            DatePublished = new DateTime(1994, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9780062068408",
                            ImageUrl = "/images/of-mice-and-men.jpg",
                            Language = "English",
                            Price = 166,
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Ernest Hemingway",
                            DatePublished = new DateTime(1994, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9780062068408",
                            ImageUrl = "/images/old-man-and-the-sea.jpg",
                            Language = "English",
                            Price = 84,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Cormac McCarthy",
                            DatePublished = new DateTime(2007, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "loreim ipsum",
                            ISBN = "9780307386458",
                            ImageUrl = "/images/the-road.jpg",
                            Language = "English",
                            Price = 95,
                            Title = "The Road"
                        });
                });

            modelBuilder.Entity("MVCP_BookStore.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MVCP_BookStore.Models.CartItem", b =>
                {
                    b.HasOne("MVCP_BookStore.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
